// apps/website/src/components/trading/symbol-summary-list.tsx
import { component$ } from '@builder.io/qwik';
import { SymbolSummary } from '@mm/api-types';
import { dateFormatDate, formatLargeNumber, roundNDigits } from '@mm/shared/general-util';
import { symbolUrl } from '../utils';
import { PercentageIncrease } from './percentage-increase';

export type SymbolSummaryProps = {
  summary?: SymbolSummary | null;
};

export const SymbolSummaryList = component$<SymbolSummaryProps>(({ summary }) => {
  const symbolUrlMerged = `${symbolUrl}/${summary?.id}`;

  return (
    <div class="flex flex-wrap justify-between @container">
      {/* company name */}
      <div class="g-item-wrapper">
        <div>Company Name</div>
        <div class="flex items-center gap-2">
          <img src={symbolUrlMerged} alt="Asset Image" class="w-6 h-6" />
          <span class="hidden @md:block">{summary?.profile?.companyName}</span>
          <span class="block @md:hidden">{summary?.id}</span>
        </div>
      </div>

      {/* sector */}
      <div class="g-item-wrapper">
        <span>Sector</span>
        <span>{summary?.profile?.sector ?? 'N/A'}</span>
      </div>

      {/* CEO */}
      <div class="g-item-wrapper">
        <span>CEO</span>
        <span>{summary?.profile?.ceo ?? 'N/A'}</span>
      </div>

      {/* employees */}
      <div class="g-item-wrapper">
        <span>Employees</span>
        <span>~{summary?.profile?.fullTimeEmployees}</span>
      </div>

      {/* market cap. */}
      <div class="g-item-wrapper">
        <span>Market Cap.</span>
        <span>
          {summary ? formatLargeNumber(summary.quote.price * summary.quote.sharesOutstanding, false, true) : 'N/A'}
        </span>
      </div>

      {/* price */}
      <div class="g-item-wrapper">
        <span>Price</span>
        <div class="flex items-center gap-2">
          <PercentageIncrease
            value={summary?.quote?.price}
            valueToCompare={summary?.quote?.previousClose}
            isPrice={true}
          />
        </div>
      </div>

      {/* volume */}
      <div class="g-item-wrapper">
        <span>Volume</span>
        <div class="flex items-center gap-2">
          <PercentageIncrease
            value={summary?.quote?.volume}
            valueToCompare={summary?.quote?.avgVolume}
            isPrice={false}
          />
        </div>
      </div>

      {/* PE */}
      <div class="g-item-wrapper">
        <span>PE / EPS</span>
        <span>
          {roundNDigits(summary?.quote.pe)} / {roundNDigits(summary?.quote?.eps)}
        </span>
      </div>

      {/* earnings */}
      <div class="g-item-wrapper">
        <span>Earnings</span>
        <span>
          {summary?.quote?.earningsAnnouncement
            ? dateFormatDate(summary.quote.earningsAnnouncement, 'MMMM d, y')
            : 'N/A'}
        </span>
      </div>
    </div>
  );
});

// libs/modules/market-stocks/ui/src/lib/components/lists/symbol-summary-list/symbol-summary-list.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, input } from '@angular/core';
import { MatChipsModule } from '@angular/material/chips';
import { SymbolSummary } from '@mm/api-types';
import {
  DefaultImgDirective,
  LargeNumberFormatterPipe,
  PercentageIncreaseDirective,
  PriceChangeItemSelectorPipe,
} from '@mm/shared/ui';
import { RecommendationDirective } from '../../../directives';

@Component({
  selector: 'app-symbol-summary-list',
  standalone: true,
  imports: [
    CommonModule,
    LargeNumberFormatterPipe,
    PercentageIncreaseDirective,
    RecommendationDirective,
    MatChipsModule,
    PriceChangeItemSelectorPipe,
    DefaultImgDirective,
  ],
  template: `
    <div class="flex flex-wrap justify-between p-3">
      <ng-container *ngTemplateOutlet="priceChange; context: { name: '5 days', key: '5D' }"></ng-container>
      <ng-container *ngTemplateOutlet="priceChange; context: { name: '6 months', key: '6M' }"></ng-container>
      <ng-container *ngTemplateOutlet="priceChange; context: { name: '1 year', key: '1Y' }"></ng-container>
      <div class="hidden sm:block">
        <ng-container *ngTemplateOutlet="priceChange; context: { name: '5 years', key: '5Y' }"></ng-container>
      </div>
    </div>

    <div class="g-item-wrapper">
      <div>Company Name</div>
      <div class="flex items-center gap-2">
        <img appDefaultImg imageType="symbol" [src]="symbolSummary().id" alt="Asset Image" class="w-6 h-6" />
        <span>{{ symbolSummary().profile?.companyName }}</span>
      </div>
    </div>

    <div class="g-item-wrapper">
      <span>Sector</span>
      <mat-chip-listbox>
        <mat-chip class="m-0" color="primary">{{ symbolSummary().profile?.sector }}</mat-chip>
      </mat-chip-listbox>
    </div>

    <div class="g-item-wrapper">
      <span>CEO</span>
      <span>{{ !!symbolSummary().profile?.ceo ? symbolSummary().profile?.ceo : 'N/A' }}</span>
    </div>

    <div class="g-item-wrapper">
      <span>Market Cap.</span>
      <span>{{ symbolSummary().quote.price * symbolSummary().quote.sharesOutstanding | largeNumberFormatter }}</span>
    </div>

    <div class="g-item-wrapper">
      <span>Price</span>
      <div class="flex items-center gap-2">
        <span>{{ symbolSummary().quote.price | currency }}</span>
        <span
          appPercentageIncrease
          [useCurrencySign]="true"
          [hideValueOnXsScreen]="true"
          [currentValues]="{
            hideValue: false,
            value: symbolSummary().quote.price,
            valueToCompare: symbolSummary().quote.previousClose
          }"
        ></span>
      </div>
    </div>

    <div class="g-item-wrapper">
      <span>Volume</span>
      <div class="flex items-center gap-2">
        <span>{{ symbolSummary().quote.volume | largeNumberFormatter }}</span>
        <span
          appPercentageIncrease
          [useCurrencySign]="false"
          [hideValueOnXsScreen]="true"
          [currentValues]="{
            hideValue: false,
            value: symbolSummary().quote.volume,
            valueToCompare: symbolSummary().quote.avgVolume
          }"
        ></span>
      </div>
    </div>

    <div class="g-item-wrapper">
      <span>PE / EPS</span>
      <span>{{ symbolSummary().quote.pe | number: '1.2-2' }} / {{ symbolSummary().quote.eps | number: '1.2-2' }}</span>
    </div>

    <!-- <div class="g-item-wrapper">
  <span>Rating</span>
  <div class="flex items-center gap-2">
    <span>{{ symbolSummary().rating?.rating ?? 'N/A' }}</span>
    <div>(<span [appRecommendation]="symbolSummary().rating?.ratingScore"></span>)</div>
  </div>
</div> -->

    <div class="g-item-wrapper">
      <span>Earnings</span>
      <span>{{
        symbolSummary().quote.earningsAnnouncement
          ? (symbolSummary().quote.earningsAnnouncement | date: 'MMMM d, y')
          : 'N/A'
      }}</span>
    </div>

    <!-- template render price change -->
    <ng-template #priceChange let-name="name" let-key="key">
      <div class="grid items-center justify-center gap-2">
        <span>{{ name }}</span>
        <span
          appPercentageIncrease
          [useCurrencySign]="false"
          [changeValues]="{
            changePercentage: symbolSummary().priceChange | priceChangeItemSelector: key
          }"
        ></span>
      </div>
    </ng-template>
  `,
  styles: `
    :host {
      display: block;
    }
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SymbolSummaryListComponent {
  symbolSummary = input.required<SymbolSummary>();
}
